import React, { useRef, useEffect, useMemo, useState } from 'react';
import { Canvas, useFrame } from '@react-three/fiber';
import { OrbitControls, Line } from '@react-three/drei';
import ThickArrowHelper from './ThickArrowHelper.jsx';
import { ketWidth, drawKet } from './ket.js';
import * as THREE from 'three';
import './App.css';

/********** Constants and initial values **********/
const SPHERE_INITIAL_CAMERA_POSITION = [3.6, 2.4, -3.6];
const SPHERE_INITIAL_CAMERA_TARGET = [0, 0.32, 0];
const SPHERE_AXIS_EXTENT = 1.3;  // Helps determine how far axis arrows and axis labels are drawn beyond the sphere itself

/********** UI components and helpers **********/

// For rendering a label, slider, AND textbox all at once
function SliderPlusTextboxControl({ label, valueNum, onChangeNum, min, max, step, disabled = false }) {
  return (
    <div className="control-group">
      <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
        <label style={{ margin: '0em 0em' }}>{label}</label> {/*: {valueNum.toFixed(1)}*/}
        <input
          type="range"
          min={min}
          max={max}
          step={step}
          value={valueNum}
          onChange={(e) => onChangeNum(parseFloat(e.target.value))}
          style={{ flex: 1 }}
          disabled={disabled}
        />
        <input
          type="number"
          min={min}
          max={max}
          step={step}
          value={valueNum}
          onChange={(e) => {
            const v = parseFloat(e.target.value);
            if (!Number.isNaN(v)) onChangeNum(v);
          }}
          style={{ width: '70px', padding: '2px' }}
          disabled={disabled}
        />
      </div>
    </div>
  );
}

/************************************************
*
* Helpers for sphere drawing
*
************************************************/

// Maps a physics-space Bloch vector (x, y, z) -- z the polar/quantization
// axis -- to the Three.js scene's (x, y, z), where y is "up" by convention.
// Three.js's vertical axis needs to receive z, but simply swapping the last
// two components results in a left-handed coordinate system (said differently,
// +z points the wrong way). So negate the last axis. Everything drawn
// on the sphere -- the state arrow, the axis arrows, the graticule -- goes
// through this one function, so the whole scene shares one consistent,
// orientation-preserving convention.
function blochToThree(x, y, z) {
  return new THREE.Vector3(x, z, -y);
}

// Bloch-vector coordinates for a pure spin-1/2 state, parametrized the
// standard way: |psi> = cos(theta/2)|0> + e^{i phi} sin(theta/2)|1>, with
// theta in [0, pi] measured from the +z axis and phi in [0, 2*pi) measured
// azimuthally from +x toward +y. (x, y, z) below are the spin/Pauli
// expectation values <sigma_x>, <sigma_y>, <sigma_z> -- equivalently
// 2<Sx>/hbar etc. -- which automatically land on the unit sphere for any
// pure state. 
function blochVectorFromState(theta, phi) {
  const x = Math.sin(theta) * Math.cos(phi);
  const y = Math.sin(theta) * Math.sin(phi);
  const z = Math.cos(theta);
  return { x, y, z };
}

// AI taught me a new word: a "graticule" is a set of intersecting lines on a
// map that show a sphere's latitude (parallels) and longitude (meridians).
// One full ring of the sphere's orthogonal graticule, radius 1. Generated by
// holding one Bloch-vector component at zero and sweeping the other two,
// then mapped through blochToThree -- so every curve on the sphere shares
// the exact same physics-to-scene transform as the state arrow and the axis
// arrows below, rather than each needing its own hand-derived sign.
// This function generates the points which are then drawn by a "Line".
// More segments = smoother-looking ring.
function graticuleRing(fixedAxis, segments = 96) {
  const pts = [];
  for (let i = 0; i <= segments; i++) {
    const t = (i / segments) * Math.PI * 2;
    const c = Math.cos(t), s = Math.sin(t);
    if (fixedAxis === 'z') pts.push(blochToThree(c, s, 0));       // x-y equator
    else if (fixedAxis === 'y') pts.push(blochToThree(c, 0, s));  // x-z meridian
    else pts.push(blochToThree(0, c, s));                          // y-z meridian
  }
  return pts;
}

// Drawn once per label text onto an offscreen 2D canvas, then used as a
// sprite texture. Sprites always billboard to face the camera, which is
// exactly what a floating axis label wants -- and unlike drei's <Html>,
// there's no DOM/CSS layer whose positioning can go wrong relative to the
// surrounding page.
function makeTextSpriteTexture(text, { color = '#333333', fontSizePx = 64 } = {}) {
  // Rendered well above the on-screen size the label actually ends up at, so
  // there's plenty of texel density to spare -- then sampled with plain
  // linear filtering and no mipmap chain, which for a mild downscale looks
  // crisper than relying on WebGL's own mip selection (the previous, blurry
  // result) or on the browser's own upscaling of a lower-res source.
  const supersample = 4;
  const canvas = document.createElement('canvas');
  const ctx = canvas.getContext('2d');
  const font = `bold ${fontSizePx * supersample}px sans-serif`;
  ctx.font = font;
  const textWidth = ctx.measureText(text).width;
  const padding = fontSizePx * supersample * 0.3;
  canvas.width = Math.ceil(textWidth + padding * 2);
  canvas.height = Math.ceil(fontSizePx * supersample * 1.4);
  ctx.font = font;
  ctx.fillStyle = color;
  ctx.textBaseline = 'middle';
  ctx.textAlign = 'center';
  ctx.fillText(text, canvas.width / 2, canvas.height / 2);
  const texture = new THREE.CanvasTexture(canvas);
  //texture.generateMipmaps = false;
  texture.minFilter = THREE.LinearFilter;
  texture.magFilter = THREE.LinearFilter;
  texture.needsUpdate = true;
  return { texture, aspect: canvas.width / canvas.height };
}
// Actual axis label, using the sprite code from above.
function AxisLabel({ text, position, size = 0.28 }) {
  const { texture, aspect } = useMemo(() => makeTextSpriteTexture(text), [text]);
  return (
    <sprite position={position} scale={[size * aspect, size, 1]}>
      <spriteMaterial map={texture} transparent depthWrite={false} />
    </sprite>
  );
}
// Same idea as makeTextSpriteTexture, but for a pole/axis label like
// "|+>_z": the ket itself is drawn as vector shapes (see ket.js) rather
// than text, so its vertical alignment can't drift with whatever font
// "sans-serif" resolves to. Only the axis subscript is real text.
function makeKetSpriteTexture(sign, axis, { color = '#333333', sizePx = 64 } = {}) {
  const supersample = 4;
  const ketSize = sizePx * supersample;
  const subPx = ketSize * 0.5;

  const canvas = document.createElement('canvas');
  const ctx = canvas.getContext('2d');
  ctx.font = `bold ${subPx}px sans-serif`;
  const subWidth = ctx.measureText(axis).width;

  const gap = ketSize * -0.06;
  const padding = ketSize * 0.25;
  const kWidth = ketWidth(ketSize);
  const totalWidth = kWidth + gap + subWidth;

  canvas.width = Math.ceil(totalWidth + padding * 2);
  canvas.height = Math.ceil(ketSize * 1.3);

  ctx.fillStyle = color;
  const startX = (canvas.width - totalWidth) / 2;
  const midY = canvas.height / 2;

  drawKet(ctx, startX, midY, ketSize, sign);

  ctx.font = `bold ${subPx}px sans-serif`;
  ctx.textBaseline = 'middle';
  ctx.fillText(axis, startX + kWidth + gap, midY + ketSize * 0.4);

  const texture = new THREE.CanvasTexture(canvas);
  texture.minFilter = THREE.LinearFilter;
  texture.magFilter = THREE.LinearFilter;
  texture.needsUpdate = true;
  return { texture, aspect: canvas.width / canvas.height };
}

function KetLabel({ sign, axis, position, size = 0.20 }) {
  const { texture, aspect } = useMemo(() => makeKetSpriteTexture(sign, axis), [sign, axis]);
  return (
    <sprite position={position} scale={[size * aspect, size, 1]}>
      <spriteMaterial map={texture} transparent depthWrite={false} />
    </sprite>
  );
}

// For the sake of reducing overhead on updates that happen every frame
// (like animations), ThickArrowHelper has an ref/imperative handle structure
// that lets us reach in and set the arrow's direction directly, avoiding
// the overhead of the whole React re-render cycle. 
// So for arrows that need updating every frame, we directly attach a useFrame
// callback that reaches in and modifies the direction directly.
function MovingArrow({ theta, phi, length, color, headLength, headWidth, shaftWidth }) {
  const arrowRef = useRef();
  useFrame(() => {
    const { x, y, z } = blochVectorFromState(theta, phi);
    arrowRef.current?.setDirection(blochToThree(x, y, z));
  });
  return (
    <ThickArrowHelper ref={arrowRef} dir={new THREE.Vector3(1, 0, 0)} origin={new THREE.Vector3(0, 0, 0)} length={length} color={color} headLength={headLength} headWidth={headWidth} shaftWidth={shaftWidth} />
  );
}

function BlochSphere({ spinState, magneticField }) {
  const controlsRef = useRef();
  // Can't use controls.reset(), since target0/position0 get captured before
  // drei applies the `target` prop below, so reset() would snap to the wrong
  // point. Set both explicitly instead.
  const resetView = () => {
    const controls = controlsRef.current;
    if (!controls) return;
    controls.object.position.set(...SPHERE_INITIAL_CAMERA_POSITION);
    controls.target.set(...SPHERE_INITIAL_CAMERA_TARGET);
    controls.update();
  };

  const equatorXY = useMemo(() => graticuleRing('z'), []);
  const meridianXZ = useMemo(() => graticuleRing('y'), []);
  const meridianYZ = useMemo(() => graticuleRing('x'), []);

  return (
    // position: 'relative' + the button's position: 'absolute' below keeps
    // the button entirely out of the surrounding flex layout -- it overlays
    // the canvas rather than becoming a sibling flex item, so it can't
    // affect the heading/canvas alignment above it.
    <div style={{ position: 'relative', width: '100%', height: '100%' }}>
      <Canvas camera={{ position: SPHERE_INITIAL_CAMERA_POSITION, fov: 35 }} style={{ width: '100%', height: '100%' }}>
        <mesh>
          <sphereGeometry args={[1, 32, 32]} />
          <meshBasicMaterial color="gray" transparent opacity={0.25} side={THREE.DoubleSide} depthWrite={false} />
        </mesh>

        <Line points={equatorXY} color="gray" lineWidth={1} dashed dashSize={0.06} gapSize={0.05} />
        <Line points={meridianXZ} color="gray" lineWidth={1} dashed dashSize={0.06} gapSize={0.05} />
        <Line points={meridianYZ} color="gray" lineWidth={1} dashed dashSize={0.06} gapSize={0.05} />

        <ThickArrowHelper dir={blochToThree(1, 0, 0)} origin={new THREE.Vector3(0, 0, 0)} length={SPHERE_AXIS_EXTENT} color={0x000000} headLength={0.09} headWidth={0.06} shaftWidth={3.0} />
        <ThickArrowHelper dir={blochToThree(0, 1, 0)} origin={new THREE.Vector3(0, 0, 0)} length={SPHERE_AXIS_EXTENT} color={0x000000} headLength={0.09} headWidth={0.06} shaftWidth={3.0} />
        <ThickArrowHelper dir={blochToThree(0, 0, 1)} origin={new THREE.Vector3(0, 0, 0)} length={SPHERE_AXIS_EXTENT} color={0x000000} headLength={0.09} headWidth={0.06} shaftWidth={3.0} />

        <KetLabel sign="+" axis="x" position={blochToThree(SPHERE_AXIS_EXTENT + 0.2, 0, 0).toArray()} />
        <KetLabel sign="-" axis="x" position={blochToThree(-(SPHERE_AXIS_EXTENT + 0.2), 0, 0).toArray()} />
        <KetLabel sign="+" axis="y" position={blochToThree(0, SPHERE_AXIS_EXTENT + 0.2, 0).toArray()} />
        <KetLabel sign="-" axis="y" position={blochToThree(0, -(SPHERE_AXIS_EXTENT + 0.2), 0).toArray()} />
        <KetLabel sign="+" axis="z" position={blochToThree(0, 0, SPHERE_AXIS_EXTENT + 0.2).toArray()} />
        <KetLabel sign="-" axis="z" position={blochToThree(0, 0, -(SPHERE_AXIS_EXTENT + 0.2)).toArray()} />

        {/* For the spin state */}
        <MovingArrow theta={spinState.theta} phi={spinState.phi} length={1} color={0xcc0000} headLength={0.12} headWidth={0.08} shaftWidth={5.0} />
        {/* For the B-field */}
        <MovingArrow theta={magneticField[0].theta} phi={magneticField[0].phi} length={1} color={0x0066cc} headLength={0.12} headWidth={0.08} shaftWidth={5.0} />

        <OrbitControls ref={controlsRef} target={SPHERE_INITIAL_CAMERA_TARGET} />
      </Canvas>

      <button
        className="control-button"
        onClick={resetView}
        style={{
          position: 'absolute',
          bottom: '10px',
          right: '10px',
          width: '60px',
          height: '60px',
          padding: '2px',
          margin: 0,
          fontSize: '0.8rem',
          lineHeight: 1.15,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          textAlign: 'center',
        }}
      >
        Reset View
      </button>
    </div>
  );
}

export default function App() {
  const [controlBools, setControlBools] = useState({
    showSphere: true,             // Displaying the sphere
    advancedBField: false         // For when the user is specifying an advanced magnetic field
  });
  // Spin state at t = 0, set by two angles
  const [initialSpinState, setInitialSpinState] = useState({ theta: 0, phi: 0 });
  // Every element of this array should have a theta, phi, magnitude, omega, and phase (at t=0) specifying it
  const [magneticField, setMagneticField] = useState([{ mag: 0, theta: 0, phi: 0, omega: 0, phase: 0 }]);

  // For setting just one property of one component of a magnetic field
  // Usage example: updateFieldComponent(0, { theta: parseFloat(e.target.value) })
  function updateFieldComponent(index, patch) {
    setMagneticField(prev => prev.map((c, i) => (i === index ? { ...c, ...patch } : c)));
  }
  // For adding and removing components of a magnetic field
  const addFieldComponent = () =>
    setMagneticField(prev => [...prev, { mag: 1, theta: 0, phi: 0, omega: 0 }]);
  const removeFieldComponent = (index) =>
    setMagneticField(prev => prev.filter((_, i) => i !== index));

  return (
    <div className="app-layout">
      {/* Main Canvas Area */}
      <div className="canvas-area">
        {/*<SpherePanel controlBools={controlBools} />*/}
        <BlochSphere spinState={initialSpinState} magneticField={magneticField} />
      </div>

      {/* Right Sidebar */}
      <aside className="sidebar">
        <div className="sidebar-content">
          <div className="panel-controls">
            <div>
              <h3>Spin State at t = 0</h3>
              <div className="control-group">
                <SliderPlusTextboxControl
                  label="θ (degrees)"
                  valueNum={(initialSpinState.theta * 180 / Math.PI).toFixed(1)}
                  onChangeNum={(val) => {setInitialSpinState({ ...initialSpinState, theta: val*Math.PI/180 })}}
                  min={0.0}
                  max={180.0}
                  step={0.01}
                />
                <SliderPlusTextboxControl
                  label="φ (degrees)"
                  valueNum={(initialSpinState.phi * 180 / Math.PI).toFixed(1)}
                  onChangeNum={(val) => {setInitialSpinState({ ...initialSpinState, phi: val*Math.PI/180 })}}
                  min={-180.0}
                  max={180.0}
                  step={0.01}
                />
              </div>

              <hr className="sidebar-divider" />
              
              <h3>Magnetic Field</h3>

              <div className="control-group">
                <SliderPlusTextboxControl
                  label="θ (degrees)"
                  valueNum={(magneticField[0].theta * 180 / Math.PI).toFixed(1)}
                  onChangeNum={(val) => {updateFieldComponent(0, { theta: parseFloat(val*Math.PI/180) })}}
                  min={0.0}
                  max={180.0}
                  step={0.01}
                />
                <SliderPlusTextboxControl
                  label="φ (degrees)"
                  valueNum={(magneticField[0].phi * 180 / Math.PI).toFixed(1)}
                  onChangeNum={(val) => {updateFieldComponent(0, { phi: parseFloat(val*Math.PI/180) })}}
                  min={-180.0}
                  max={180.0}
                  step={0.01}
                />
              </div>

              <hr className="sidebar-divider" />

              <h3>Display Options</h3>
              <div className="control-group" style={{ marginTop: '1.0em' }}>
                <button className={`control-button ${controlBools.showSphere ? 'active' : ''}`} onClick={() => setControlBools({ ...controlBools, showSphere: !controlBools.showSphere })}>
                  {controlBools.showSphere ? 'Hide sphere' : 'Show sphere'}
                </button>
              </div>

              <div className="control-group" style={{ marginTop: '1.0em' }}>
                <button className={`control-button ${controlBools.advancedBField ? 'active-special' : ''}`} onClick={() => setControlBools({ ...controlBools, advancedBField: !controlBools.advancedBField })}>
                  Advanced
                </button>
              </div>
            </div>
          </div>
        </div>
      </aside>
    </div>
  );
}